name: Nightly Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - name: Build
        run: |
          zig build -Doptimize=ReleaseFast
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: autoapi.dll
          path: zig-out/bin